version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build: 
    docker:
      - image: circleci/node:4.8.2-jessie

    working_directory: ~/repo

    steps:
      - run: echo build step

  test:
    docker:
      - image: circleci/node:4.8.2-jessie

    working_directory: ~/repo

    steps:
      - run: echo test step

workflows:
  version: 2.1
  build-and-test: 
    jobs:
      - build
      - test:
          requires:
            - build

